package com.urlxl.mail.contacts

import com.urlxl.mail.data.ContactEntity
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

private val mapperJson = Json { ignoreUnknownKeys = true }

fun ContactDto.toEntity(): ContactEntity = ContactEntity(
    uid = uid,
    rev = rev,
    createdAt = createdAt,
    updatedAt = updatedAt,
    fn = fn,
    givenName = givenName,
    familyName = familyName,
    middleName = middleName,
    prefix = prefix,
    suffix = suffix,
    nickname = nickname,
    org = org,
    title = title,
    notes = notes,
    birthday = birthday,
    emailsJson = mapperJson.encodeToString(emails),
    phonesJson = mapperJson.encodeToString(phones),
    addressesJson = mapperJson.encodeToString(addresses),
    groupIDsJson = mapperJson.encodeToString(groupIDs),
    photoRef = photoRef,
    pgpKey = pgpKey,
    imsJson = mapperJson.encodeToString(ims),
    websitesJson = mapperJson.encodeToString(websites),
    relationsJson = mapperJson.encodeToString(relations),
    eventsJson = mapperJson.encodeToString(events),
    phoneticGivenName = phoneticGivenName,
    phoneticFamilyName = phoneticFamilyName,
    department = department,
    customFieldsJson = mapperJson.encodeToString(customFields),
    pronouns = pronouns,
    isSelf = isSelf,
)

fun ContactEntity.toDto(): ContactDto = ContactDto(
    uid = uid,
    rev = rev,
    createdAt = createdAt,
    updatedAt = updatedAt,
    fn = fn,
    givenName = givenName,
    familyName = familyName,
    middleName = middleName,
    prefix = prefix,
    suffix = suffix,
    nickname = nickname,
    org = org,
    title = title,
    notes = notes,
    birthday = birthday,
    emails = runCatching { mapperJson.decodeFromString<List<ContactFieldDto>>(emailsJson) }.getOrDefault(emptyList()),
    phones = runCatching { mapperJson.decodeFromString<List<ContactFieldDto>>(phonesJson) }.getOrDefault(emptyList()),
    addresses = runCatching { mapperJson.decodeFromString<List<ContactAddressDto>>(addressesJson) }.getOrDefault(emptyList()),
    groupIDs = runCatching { mapperJson.decodeFromString<List<String>>(groupIDsJson) }.getOrDefault(emptyList()),
    photoRef = photoRef,
    pgpKey = pgpKey,
    ims = runCatching { mapperJson.decodeFromString<List<ContactImDto>>(imsJson) }.getOrDefault(emptyList()),
    websites = runCatching { mapperJson.decodeFromString<List<ContactUrlDto>>(websitesJson) }.getOrDefault(emptyList()),
    relations = runCatching { mapperJson.decodeFromString<List<ContactRelationDto>>(relationsJson) }.getOrDefault(emptyList()),
    events = runCatching { mapperJson.decodeFromString<List<ContactEventDto>>(eventsJson) }.getOrDefault(emptyList()),
    phoneticGivenName = phoneticGivenName,
    phoneticFamilyName = phoneticFamilyName,
    department = department,
    customFields = runCatching { mapperJson.decodeFromString<List<ContactCustomFieldDto>>(customFieldsJson) }.getOrDefault(emptyList()),
    pronouns = pronouns,
    isSelf = isSelf,
)
